/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author Noah
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String Op;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnBS = new javax.swing.JButton();
        jBtnCE = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnPM = new javax.swing.JButton();
        jBtnPlus = new javax.swing.JButton();
        jBtnDigit9 = new javax.swing.JButton();
        jBtnDigit7 = new javax.swing.JButton();
        jBtnDigit8 = new javax.swing.JButton();
        jBtnDigit4 = new javax.swing.JButton();
        jBtnDigit5 = new javax.swing.JButton();
        jBtnDigit6 = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jBtnMultiply = new javax.swing.JButton();
        jBtnDivide = new javax.swing.JButton();
        jBtnEquals = new javax.swing.JButton();
        jBtnDecimal = new javax.swing.JButton();
        jBtnDigit0 = new javax.swing.JButton();
        jBtnDigit1 = new javax.swing.JButton();
        jBtnDigit2 = new javax.swing.JButton();
        jBtnDigit3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 60));

        jbtnBS.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jbtnBS.setText("←");
        jbtnBS.setToolTipText("");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 70));

        jBtnCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnCE.setText("CE");
        jBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 70));

        jBtnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, 70));

        jBtnPM.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jBtnPM.setText("±");
        jBtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 80, 70));

        jBtnPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPlus.setText("+");
        jBtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 80, 70));

        jBtnDigit9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit9.setText("9");
        jBtnDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 70));

        jBtnDigit7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit7.setText("7");
        jBtnDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 70));

        jBtnDigit8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit8.setText("8");
        jBtnDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, 70));

        jBtnDigit4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit4.setText("4");
        jBtnDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 70));

        jBtnDigit5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit5.setText("5");
        jBtnDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 80, 70));

        jBtnDigit6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit6.setText("6");
        jBtnDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 70));

        jBtnMinus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnMinus.setText("-");
        jBtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 80, 70));

        jBtnMultiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnMultiply.setText("*");
        jBtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 80, 70));

        jBtnDivide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDivide.setText("/");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 80, 70));

        jBtnEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEquals.setText("=");
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 80, 70));

        jBtnDecimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDecimal.setText(".");
        jBtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 80, 70));

        jBtnDigit0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit0.setText("0");
        jBtnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 80, 70));

        jBtnDigit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit1.setText("1");
        jBtnDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, 70));

        jBtnDigit2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit2.setText("2");
        jBtnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, 70));

        jBtnDigit3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDigit3.setText("3");
        jBtnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 80, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void EnterNumbers(String q){
        String Nums = jtxtResult.getText() +q;
        jtxtResult.setText(Nums);
    }
    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    private void jBtnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jBtnDigit9ActionPerformed

    private void jBtnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jBtnDigit7ActionPerformed

    private void jBtnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit6ActionPerformed
       EnterNumbers("6");
    }//GEN-LAST:event_jBtnDigit6ActionPerformed

    private void jBtnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit8ActionPerformed
       EnterNumbers("8");
    }//GEN-LAST:event_jBtnDigit8ActionPerformed

    private void jBtnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jBtnDigit1ActionPerformed

    private void jBtnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jBtnDigit2ActionPerformed

    private void jBtnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jBtnDigit3ActionPerformed

    private void jBtnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jBtnDigit4ActionPerformed

    private void jBtnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jBtnDigit5ActionPerformed

    private void jBtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigit0ActionPerformed
       EnterNumbers("0");
    }//GEN-LAST:event_jBtnDigit0ActionPerformed

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivideActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "/";
    }//GEN-LAST:event_jBtnDivideActionPerformed

    private void jBtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecimalActionPerformed
       if(! jtxtResult.getText().contains(".")){
        jtxtResult.setText(jtxtResult.getText() +jBtnDecimal.getText());
    }
    }//GEN-LAST:event_jBtnDecimalActionPerformed

    private void jBtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplyActionPerformed
         NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "*";
    }//GEN-LAST:event_jBtnMultiplyActionPerformed

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "-";
    }//GEN-LAST:event_jBtnMinusActionPerformed

    private void jBtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusActionPerformed
       NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "+";
    }//GEN-LAST:event_jBtnPlusActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
       jtxtResult.setText("");
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCEActionPerformed
         jtxtResult.setText("");
         String Fn, Sn;
         Fn = String.valueOf(NumEnter1);
         Sn = String.valueOf(NumEnter2);
         
         Fn ="";
         Sn = "";
    }//GEN-LAST:event_jBtnCEActionPerformed

    private void jBtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPMActionPerformed
       double nums = Double.parseDouble(String.valueOf((jtxtResult.getText())));
       nums = nums *(-1);
       jtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jBtnPMActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        String bk = null;
        if(jtxtResult.getText().length() >0){
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() -1);
            bk = sb.toString();
            
            jtxtResult.setText(bk);
        }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualsActionPerformed
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        if(Op== "+"){
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }else if(Op== "-"){
            Result = NumEnter1 - NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }else if(Op== "/"){
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }else if(Op== "*"){
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jBtnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnDecimal;
    private javax.swing.JButton jBtnDigit0;
    private javax.swing.JButton jBtnDigit1;
    private javax.swing.JButton jBtnDigit2;
    private javax.swing.JButton jBtnDigit3;
    private javax.swing.JButton jBtnDigit4;
    private javax.swing.JButton jBtnDigit5;
    private javax.swing.JButton jBtnDigit6;
    private javax.swing.JButton jBtnDigit7;
    private javax.swing.JButton jBtnDigit8;
    private javax.swing.JButton jBtnDigit9;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnMultiply;
    private javax.swing.JButton jBtnPM;
    private javax.swing.JButton jBtnPlus;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
